baseURL: https://joselondono.co/
title: Jos√© Londo√±o
theme: PaperMod
languageCode: en
defaultContentLanguage: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
    defaultTheme: light
    DateFormat: "January 2, 2006"

    profileMode:
        enabled: true
        title: "Hi! I'm Jos√© Londo√±o üëãüèª"
        imageUrl: "assets/me.jpg" 
        imageTitle: "Me" # optional
        imageWidth: 350 # custom size
        imageHeight: 350 # custom size

    socialIcons:
        - name: "Twitter"
          url: "https://twitter.com/jlondonobo"
        - name: "Github"
          url: "https://github.com/jlondonobo"
        - name: "Email"
          url: "mailto:j.londonobo@gmail.com"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/jose-londono-botero"
        - name: "Medium"
          url: "https://jlondonobo.medium.com/"

    ShowShareButtons: false
    ShowReadingTime: true
    ShowCodeCopyButtons: true


pluralizelisttitles: false


