baseURL: https://joselondono.co/
languageCode: en
defaultContentLanguage: en
title: Jos√© Londo√±o

params:
    defaultTheme: light

    profileMode:
        enabled: true
        title: "Hi! I'm Jos√© Londo√±o üëãüèª"
        subtitle: "I'm a data scientist from Medell√≠n, Colombia. üá®üá¥"
        imageUrl: "assets/me.jpg" 
        imageTitle: "Me" # optional
        imageWidth: 350 # custom size
        imageHeight: 350 # custom size
        buttons:
          - name: Blog
            url: "/blog"

    socialIcons:
        - name: "Twitter"
          url: "https://twitter.com/jlondonobo"
        - name: "Github"
          url: "https://github.com/jlondonob"
        - name: "Email"
          url: "mailto:j.londonobo@gmail.com"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/jose-londono-botero"
        - name: "Medium"
          url: "https://jlondonobo.medium.com/"

    ShowShareButtons: true

    ShowReadingTime: true

    ShowCodeCopyButtons: true


theme: PaperMod


